#!/bin/bash
echo "DOCKER REPO: $DOCKER_REPO, CACHE_TAG: $CACHE_TAG, IMAGE_NAME: $IMAGE_NAME"
docker build --build-arg PYBOSSA_COMMIT=${SOURCE_BRANCH:-master} -t $IMAGE_NAME .
docker tag ${IMAGE_NAME} $(DOCKER_REPO}:latest
